### ISSUE TITLE
Create extra module in `containers-sig-*` packages with default implementations for some functions

### ISSUE THREAD

**Issue by ChShersh** [kowainik/containers-backpack#16] opened 2018-08-11 10:52 UTC
There's this useful operator:

```haskell
infixl 9 !?
(!?) :: Key k => Map k v -> k -> Maybe v
(!?) m k = lookup k m
```

And probably there exist other useful functions with default implementations. We need to collect such functions and put them near signatures. Though, good naming for module is most difficult part here...

**Comment by vrom911** [comment] 2018-09-30 08:41
Duplicate of #23

**Closed by vrom911** 2018-09-30 08:41 UTC
Labels: enhancement, signatures
